// <auto-generated />
using System;
using GameLibrary.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GameLibrary.Core.Data.Migrations
{
    [DbContext(typeof(GameLibraryDbContext))]
    [Migration("20260826034524_AddSteamIntegration")]
    partial class AddSteamIntegration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GameLibrary.Core.Games.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("ApproximateDuration")
                        .HasColumnType("integer")
                        .HasColumnName("approximate_duration");

                    b.Property<string>("CoverImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("cover_image_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("GameType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("game_type");

                    b.Property<string>("InteractionType")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("interaction_type");

                    b.Property<int?>("MaximumPlayers")
                        .HasColumnType("integer")
                        .HasColumnName("maximum_players");

                    b.Property<int?>("MinimumPlayers")
                        .HasColumnType("integer")
                        .HasColumnName("minimum_players");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("games", null, t =>
                        {
                            t.HasCheckConstraint("ck_games_approximate_duration", "approximate_duration IS NULL OR approximate_duration > 0");

                            t.HasCheckConstraint("ck_games_board_columns_video_null", "game_type = 'BoardGame' OR (approximate_duration IS NULL AND interaction_type IS NULL)");

                            t.HasCheckConstraint("ck_games_board_players_required", "game_type = 'VideoGame' OR (minimum_players IS NOT NULL AND maximum_players IS NOT NULL)");

                            t.HasCheckConstraint("ck_games_game_type", "game_type IN ('VideoGame', 'BoardGame')");

                            t.HasCheckConstraint("ck_games_interaction_type", "interaction_type IS NULL OR interaction_type IN ('Cooperative', 'Competitive')");

                            t.HasCheckConstraint("ck_games_maximum_players", "minimum_players IS NULL OR maximum_players IS NULL OR maximum_players >= minimum_players");

                            t.HasCheckConstraint("ck_games_minimum_players", "minimum_players IS NULL OR minimum_players >= 1");

                            t.HasCheckConstraint("ck_games_video_players_both_or_neither", "game_type = 'BoardGame' OR ((minimum_players IS NULL AND maximum_players IS NULL) OR (minimum_players IS NOT NULL AND maximum_players IS NOT NULL))");
                        });
                });

            modelBuilder.Entity("GameLibrary.Core.Games.GameGenre", b =>
                {
                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_id");

                    b.Property<Guid>("GenreId")
                        .HasColumnType("uuid")
                        .HasColumnName("genre_id");

                    b.HasKey("GameId", "GenreId");

                    b.HasIndex("GameId")
                        .HasDatabaseName("ix_game_genres_game_id");

                    b.HasIndex("GenreId")
                        .HasDatabaseName("ix_game_genres_genre_id");

                    b.ToTable("game_genres", (string)null);
                });

            modelBuilder.Entity("GameLibrary.Core.Games.GamePlatform", b =>
                {
                    b.Property<Guid>("LibraryEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("library_entry_id");

                    b.Property<Guid>("PlatformId")
                        .HasColumnType("uuid")
                        .HasColumnName("platform_id");

                    b.HasKey("LibraryEntryId", "PlatformId");

                    b.HasIndex("PlatformId")
                        .HasDatabaseName("ix_game_platforms_platform_id");

                    b.ToTable("game_platforms", (string)null);
                });

            modelBuilder.Entity("GameLibrary.Core.Games.Genre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_genres_name");

                    b.ToTable("genres", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Action"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Name = "RPG"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Name = "Strategy"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Name = "Simulation"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            Name = "Sports"
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            Name = "Racing"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            Name = "Fighting"
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            Name = "Shooter"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Name = "Platformer"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Name = "Puzzle"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            Name = "Horror"
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            Name = "Rhythm"
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            Name = "Party"
                        },
                        new
                        {
                            Id = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("GameLibrary.Core.Games.LibraryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AcquisitionStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("acquisition_status");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_id");

                    b.Property<string>("GameStatus")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("game_status");

                    b.Property<Guid>("LibraryId")
                        .HasColumnType("uuid")
                        .HasColumnName("library_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int?>("ProgressPercentage")
                        .HasColumnType("integer")
                        .HasColumnName("progress_percentage");

                    b.Property<int?>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<long?>("SteamAppId")
                        .HasColumnType("bigint")
                        .HasColumnName("steam_app_id");

                    b.HasKey("Id");

                    b.HasIndex("GameId")
                        .IsUnique()
                        .HasDatabaseName("ix_library_entries_game_id");

                    b.HasIndex("LibraryId")
                        .HasDatabaseName("ix_library_entries_library_id");

                    b.HasIndex("LibraryId", "SteamAppId")
                        .IsUnique()
                        .HasDatabaseName("ix_library_entries_library_id_steam_app_id")
                        .HasFilter("steam_app_id IS NOT NULL");

                    b.ToTable("library_entries", null, t =>
                        {
                            t.HasCheckConstraint("ck_library_entries_owned_status_progress", "acquisition_status = 'Owned' OR (game_status IS NULL AND progress_percentage IS NULL)");

                            t.HasCheckConstraint("ck_library_entries_progress_percentage", "progress_percentage IS NULL OR (progress_percentage BETWEEN 0 AND 100)");

                            t.HasCheckConstraint("ck_library_entries_rating", "rating IS NULL OR (rating BETWEEN 1 AND 5)");

                            t.HasCheckConstraint("ck_library_entries_steam_app_id", "steam_app_id IS NULL OR (steam_app_id BETWEEN 1 AND 4294967295)");
                        });
                });

            modelBuilder.Entity("GameLibrary.Core.Libraries.Library", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_libraries_user_id");

                    b.ToTable("libraries", (string)null);
                });

            modelBuilder.Entity("GameLibrary.Core.Platforms.Platform", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("LibraryId")
                        .HasColumnType("uuid")
                        .HasColumnName("library_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("NameNormalized")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasColumnName("name_normalized")
                        .HasComputedColumnSql("lower(name)", true);

                    b.HasKey("Id");

                    b.HasIndex("LibraryId", "NameNormalized")
                        .IsUnique()
                        .HasDatabaseName("ix_platforms_library_id_name_normalized");

                    b.ToTable("platforms", (string)null);
                });

            modelBuilder.Entity("GameLibrary.Core.PlayLog.PlayLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<Guid>("LibraryEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("library_entry_id");

                    b.Property<DateTimeOffset>("PlayedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("played_at");

                    b.HasKey("Id")
                        .HasName("pk_play_log_entries");

                    b.HasIndex("LibraryEntryId")
                        .HasDatabaseName("ix_play_log_entries_library_entry_id");

                    b.ToTable("play_log_entries", null, t =>
                        {
                            t.HasCheckConstraint("ck_play_log_entries_duration_minutes_positive", "duration_minutes IS NULL OR duration_minutes > 0");
                        });
                });

            modelBuilder.Entity("GameLibrary.Core.Steam.SteamAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("LibraryId")
                        .HasColumnType("uuid")
                        .HasColumnName("library_id");

                    b.Property<DateTimeOffset>("LinkedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("linked_at");

                    b.Property<string>("SteamId64")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("steam_id64");

                    b.HasKey("Id")
                        .HasName("pk_steam_accounts");

                    b.HasIndex("LibraryId")
                        .IsUnique()
                        .HasDatabaseName("ix_steam_accounts_library_id");

                    b.HasIndex("SteamId64")
                        .IsUnique()
                        .HasDatabaseName("ix_steam_accounts_steam_id64");

                    b.ToTable("steam_accounts", (string)null);
                });

            modelBuilder.Entity("GameLibrary.Core.Steam.SteamLinkRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("LibraryId")
                        .HasColumnType("uuid")
                        .HasColumnName("library_id");

                    b.Property<string>("StateHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("state_hash");

                    b.HasKey("Id")
                        .HasName("pk_steam_link_requests");

                    b.HasIndex("LibraryId")
                        .HasDatabaseName("ix_steam_link_requests_library_id");

                    b.HasIndex("StateHash")
                        .IsUnique()
                        .HasDatabaseName("ix_steam_link_requests_state_hash");

                    b.ToTable("steam_link_requests", null, t =>
                        {
                            t.HasCheckConstraint("ck_steam_link_requests_expires_at", "expires_at > created_at");

                            t.HasCheckConstraint("ck_steam_link_requests_state_hash", "char_length(state_hash) = 64");
                        });
                });

            modelBuilder.Entity("GameLibrary.Core.Games.GameGenre", b =>
                {
                    b.HasOne("GameLibrary.Core.Games.Game", "Game")
                        .WithMany("GameGenres")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameLibrary.Core.Games.Genre", "Genre")
                        .WithMany("GameGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("GameLibrary.Core.Games.GamePlatform", b =>
                {
                    b.HasOne("GameLibrary.Core.Games.LibraryEntry", "LibraryEntry")
                        .WithMany("GamePlatforms")
                        .HasForeignKey("LibraryEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameLibrary.Core.Platforms.Platform", "Platform")
                        .WithMany()
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LibraryEntry");

                    b.Navigation("Platform");
                });

            modelBuilder.Entity("GameLibrary.Core.Games.LibraryEntry", b =>
                {
                    b.HasOne("GameLibrary.Core.Games.Game", "Game")
                        .WithOne("LibraryEntry")
                        .HasForeignKey("GameLibrary.Core.Games.LibraryEntry", "GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GameLibrary.Core.Libraries.Library", "Library")
                        .WithMany("LibraryEntries")
                        .HasForeignKey("LibraryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Library");
                });

            modelBuilder.Entity("GameLibrary.Core.Platforms.Platform", b =>
                {
                    b.HasOne("GameLibrary.Core.Libraries.Library", "Library")
                        .WithMany("Platforms")
                        .HasForeignKey("LibraryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Library");
                });

            modelBuilder.Entity("GameLibrary.Core.PlayLog.PlayLogEntry", b =>
                {
                    b.HasOne("GameLibrary.Core.Games.LibraryEntry", "LibraryEntry")
                        .WithMany("PlayLogEntries")
                        .HasForeignKey("LibraryEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_play_log_entries_library_entries_library_entry_id");

                    b.Navigation("LibraryEntry");
                });

            modelBuilder.Entity("GameLibrary.Core.Steam.SteamAccount", b =>
                {
                    b.HasOne("GameLibrary.Core.Libraries.Library", "Library")
                        .WithOne("SteamAccount")
                        .HasForeignKey("GameLibrary.Core.Steam.SteamAccount", "LibraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Library");
                });

            modelBuilder.Entity("GameLibrary.Core.Steam.SteamLinkRequest", b =>
                {
                    b.HasOne("GameLibrary.Core.Libraries.Library", "Library")
                        .WithMany("SteamLinkRequests")
                        .HasForeignKey("LibraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Library");
                });

            modelBuilder.Entity("GameLibrary.Core.Games.Game", b =>
                {
                    b.Navigation("GameGenres");

                    b.Navigation("LibraryEntry")
                        .IsRequired();
                });

            modelBuilder.Entity("GameLibrary.Core.Games.Genre", b =>
                {
                    b.Navigation("GameGenres");
                });

            modelBuilder.Entity("GameLibrary.Core.Games.LibraryEntry", b =>
                {
                    b.Navigation("GamePlatforms");

                    b.Navigation("PlayLogEntries");
                });

            modelBuilder.Entity("GameLibrary.Core.Libraries.Library", b =>
                {
                    b.Navigation("LibraryEntries");

                    b.Navigation("Platforms");

                    b.Navigation("SteamAccount");

                    b.Navigation("SteamLinkRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
